language: java

jdk:
  - openjdk-ea
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk8

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    -
before_install:
  - chmod +x mvnw

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

notifications:
  email: false

env:
  global:
    - secure: "G0CzaHpOm0SYACoL5iVLFpJl2dGw+wG6mxuCPlHQNHMEhiBsta0OK4eqC+kFImvF4gfXh0dWNy9JspNVoH9x+BA3S+0o0kML0AuNq6DBe7A+Lqkg3R5L+QfcdXIOszvkzktaK+pFYWKKuDJdGkT+2CiS/Aq44UZ1n6bvt9wctwqsR4LzJBulqyJPyZIfQlaUcVLcyoDzkD74ieqXfuEKI4bHqB0rS/1wmPkhvrG5qfqV5YPMH8LAZTmiwQrovMTlJ7jUIlLhsZ+4CE8QqcnO/1vpAezV0OMeHlo/EmsOGa5TsmaTFcBhHBxiXhvS5+YQGfAFTZkdNvcbmZpjqzfpoEHuKkk38bMIH5HpSuyWiG0GNbdeF476Pr6wCOureGKMZAUF7qs0DVaGBUqakU1Vs7+BUU6LD+v/oS+69YwTuPkaKeWYcT8JazqOMZl1iA2b5Bwvcj4JxcTEaBaBhN/955OPesb5khQNH1Ift59IGrxz2tYgQpxOPYrOcl8GlsgXCDdnb3sH0W3uVpCsLxmoRqaGmr9dLaw50Xg89Z00+wnlviRrqUjMJ1AL9XYa/yXnpYOI460SWQs/kIzwcBtgwCy/TLUyR2GtW13+qXsjNNXrRKQw0od2lj/z5nyuRdQNQRFKwnrckOYxyegN7Htn4vGtCluhTkOb3/11Oe2o9VI="

addons:
  sonarcloud:
    organization: "fartherp"
    token:
      secure: "Wntoqvu20Z4ifRuiPV72fnqfJ3x1p/gu0XN+MpqUEBXD9GBdevQhVsNWE2wcmOB136mb1OBfN80OSf+cGQiPRKKKsMSF6/TYNFENV211kmsxZwJYmyNWhnCliar21Bakw6PhzxL6x4SrUArlnFeLFkI/BwoxVS+QrzhZfdlzNBhCyIZdch2HUoMZ4ZSGiO8YJg2gEqgiB+dYly7+mN88lk6EC/W3TdrwPgv96D7UCgMme/2LJKjuWaR68ZPn66yDDVjENv+5AuPdl0ArG7xUPaabn6zq+TXktklsS0wOKxVdFuL76EIl6IFO3S9yfjDFX5P6LrHOJS4X7OtTrv8YE/9h5qEfiTv6+RlxkacXdIRzulX3494OFohzzacm1sECadIqWNN0OdAMjb0YJIVK9RMhAONWPIAmpzdA9myGNb32kdhsnSkiXxserLbiXWuxyBVqxZ8W2VYVY1+VCctYB4hG/JzRZaCH7jtXt7QNBSPKeGtbPyfbc6r6OEjsyVT1+0bjltGPUgicculrSg4JWocrfbCKiM/yRhXn0IjL3/9s+3JG6xvo4YNR7rhO5C+UghUEoBFW2PX6wMP/gyvehg9wIO/NN5BxZMX65xysztsfjE8UNM0dQ5v2QlVbSmLaucDlU8Gad5aSqvvrsHRU+HLfo/maunaFeof0mNqN2A0="